#include <stdio.h>
#include <stdlib.h>
#include <unistd.h>

#include "puppet_mnemonic.h"
#include "puppet_parser.tab.h"


extern FILE *yyin;  // Declare the global yyin variable
extern int yylineno;
extern void yylex_destroy();


int yyerror(const char *s) {
  fprintf(stderr, "Syntax error at line %d: Unexpected token: %s\n", yylineno, yylval.sval);
  return 0;
}


int main(int argc, char *argv[]) {
  char *input_filename = NULL;
  int opt;

  while ((opt = getopt(argc, argv, "f:")) != -1) {
    switch (opt) {
      case 'f':
        input_filename = optarg;
        break;
      default:
        fprintf(stderr, "Usage: %s -f <input_file>\n", argv[0]);
        return 1;
    }
  }

  if (input_filename == NULL) {
    fprintf(stderr, "The -f option with a file name is required.\n");
    return 1;
  }

  FILE *input_file = fopen(input_filename, "r");
  if (input_file == NULL) {
    perror("Error opening input file");
    return 1;
  }

  // Redirect Flex's input to the new file
  yyin = input_file;

  yyparse();  // Call the parsing function generated by Bison

  fclose(input_file);  // Close the input file

  print_nodes();
  free_nodes();

  yylex_destroy();

  return 0;
}
